# Comprobación de que datos tenemos antes de comenzar con el ETL y EDA

In [1]:
import numpy as np
import pandas as pd

### 1. Datos estructurados

In [2]:
df_agricola = pd.read_csv('datos/produccion_agricola.csv')
df_agricola.head()

,pais,codigo_iso,region,cultivo,anio,superficie_hectareas,rendimiento_ton_ha,produccion_ton,fertilizantes_kg_ha,agua_riego_m3_ha,tendencia_5_anios
0,Argentina,ARG,América del Sur,Soja,2011,4703643,2.22,10465461,105,4811,0.000536
1,Argentina,ARG,América del Sur,Maíz,2011,3371781,8.45,28485921,164,5557,0.030943
2,Argentina,ARG,América del Sur,Cebada,2011,1661577,2.77,4596917,105,6514,-0.039779
3,Argentina,ARG,América del Sur,Té,2011,188518,3.07,577886,236,8527,0.003623
4,Argentina,ARG,América del Sur,Algodón,2011,1638327,1.18,1929756,276,6925,0.007735

In [4]:
df_agricola.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   pais                  1200 non-null   object
 1   codigo_iso            1200 non-null   object
 2   region                1200 non-null   object
 3   cultivo               1200 non-null   object
 4   anio                  1200 non-null   int64
 5   superficie_hectareas  1200 non-null   int64
 6   rendimiento_ton_ha    1200 non-null   float64
 7   produccion_ton        1200 non-null   int64
 8   fertilizantes_kg_ha   1200 non-null   int64
 9   agua_riego_m3_ha      1200 non-null   int64
 10  tendencia_5_anios     1200 non-null   float64
dtypes: float64(2), int64(5), object(4)
memory usage: 103.3+ KB

In [5]:
df_ganadera = pd.read_csv('datos/produccion_ganadera.csv')
df_ganadera.head()

,pais,anio,tipo_ganado,cabezas_ganado,produccion_carne_ton,produccion_leche_lt,emisiones_ch4_ton_co2eq,intensidad_emisiones,eficiencia_carne
0,Argentina,2011,bovino,18160590,1857394,2355425160,1121740,0.062,0.1023
1,Argentina,2011,porcino,13481224,1528896,0,1984357,0.147,0.1134
2,Argentina,2011,avicola,979196737,1290153,0,10160819,0.010,0.0013
3,Argentina,2011,ovino,13789178,477282,329191349,5061273,0.367,0.0346
4,Argentina,2011,caprino,2045715,345732,454558689,284966,0.139,0.1690

In [6]:
df_ganadera.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pais                     600 non-null    object
 1   anio                     600 non-null    int64
 2   tipo_ganado              600 non-null    object
 3   cabezas_ganado           600 non-null    int64
 4   produccion_carne_ton     600 non-null    int64
 5   produccion_leche_lt      600 non-null    int64
 6   emisiones_ch4_ton_co2eq  600 non-null    int64
 7   intensidad_emisiones     600 non-null    float64
 8   eficiencia_carne         600 non-null    float64
dtypes: float64(2), int64(5), object(2)
memory usage: 42.3+ KB

In [8]:
df_precio = pd.read_csv('datos/precios_mercado.csv')
df_precio.head()

,fecha,pais,producto,precio_usd_ton,volumen_operado_ton,tendencia_30_dias,mercado_principal,precio_min_mes,precio_max_mes
0,2021-01-01,Argentina,Carne_bovina,4299.14,127922,subiendo,UE,3844.74,4517.42
1,2021-01-01,Argentina,Arroz,330.04,73231,subiendo,Sudeste Asiático,310.10,359.86
2,2021-01-01,Argentina,Maíz,210.36,11666,bajando,Japón,200.56,238.83
3,2021-01-01,Brasil,Maíz,212.91,195579,subiendo,Oriente Medio,200.25,243.04
4,2021-01-01,Brasil,Leche,356.41,136137,subiendo,UE,348.39,390.03

In [10]:
df_precio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864 entries, 0 to 863
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   fecha                864 non-null    object
 1   pais                 864 non-null    object
 2   producto             864 non-null    object
 3   precio_usd_ton       864 non-null    float64
 4   volumen_operado_ton  864 non-null    int64
 5   tendencia_30_dias    864 non-null    object
 6   mercado_principal    864 non-null    object
 7   precio_min_mes       864 non-null    float64
 8   precio_max_mes       864 non-null    float64
dtypes: float64(3), int64(1), object(5)
memory usage: 60.9+ KB

In [11]:
df_imagenes = pd.read_csv('datos/imagenes_metadata.csv')
df_imagenes.head()

,imagen_id,pais,region,fecha,indice_ndvi_promedio,indice_ndvi_min,indice_ndvi_max,indice_evi,uso_suelo_predominante,humedad_suelo_estimada,cobertura_nubes,resolucion_metros,satelite,bandas_disponibles,calidad_imagen
0,SAT_FRA_202001_000,Francia,Región Principal,2020-01-15,0.391,0.259,0.432,0.432,bosque,0.378,0.074,30,MODIS,"RGB, NIR, SWIR",media
1,SAT_ARG_202001_001,Argentina,Noroeste,2020-01-31,0.488,0.390,0.601,0.555,mixto,0.480,0.055,30,Sentinel-2,"RGB, NIR, SWIR",baja
2,SAT_CHN_202003_002,China,Región Principal,2020-03-01,0.546,0.433,0.622,0.655,urbano,0.552,0.099,20,MODIS,"RGB, NIR, SWIR",baja
3,SAT_DEU_202003_003,Alemania,Región Principal,2020-03-12,0.601,0.446,0.655,0.744,urbano,0.644,0.209,60,Sentinel-2,"RGB, NIR, SWIR",media
4,SAT_FRA_202003_004,Francia,Región Principal,2020-03-22,0.639,0.518,0.753,0.792,mixto,0.441,0.249,10,Sentinel-2,"RGB, NIR, SWIR",baja

In [12]:
df_imagenes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   imagen_id               250 non-null    object
 1   pais                    250 non-null    object
 2   region                  250 non-null    object
 3   fecha                   250 non-null    object
 4   indice_ndvi_promedio    250 non-null    float64
 5   indice_ndvi_min         250 non-null    float64
 6   indice_ndvi_max         250 non-null    float64
 7   indice_evi              250 non-null    float64
 8   uso_suelo_predominante  250 non-null    object
 9   humedad_suelo_estimada  250 non-null    float64
 10  cobertura_nubes         250 non-null    float64
 11  resolucion_metros       250 non-null    int64
 12  satelite                250 non-null    object
 13  bandas_disponibles      250 non-null    object
 14  calidad_imagen          250 non-null    object
dtypes: float64(6), int64(1), object(8)
memory usage: 29.4+ KB

### 2. Datos semi-estructurados

In [13]:
df_condiciones = pd.read_csv('datos/condiciones_climaticas.csv')
df_condiciones.head()

,anio,codigo_iso,dias_con_heladas,eventos_extremos,humedad_relativa_promedio,indice_aridez,meses_estres_hidrico,pais,precipitacion_total,region_nombre,temperatura_maxima,temperatura_minima,temperatura_promedio
0,2011,ARG,19,NaN,64,17.26,1,Argentina,1050,Pampa Húmeda,22.3,3.6,16.9
1,2011,ARG,48,NaN,82,8.63,6,Argentina,702,Cuyo,34.6,8.5,22.6
2,2011,ARG,86,NaN,61,18.37,7,Argentina,635,Patagonia,21.5,2.1,9.6
3,2011,AUS,49,NaN,59,12.24,0,Australia,1040,Murray-Darling Basin,33.9,18.1,23.6
4,2011,AUS,100,inundacion,82,10.64,1,Australia,912,Queensland Coast,34.5,9.3,23.8

In [14]:
df_condiciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   anio                       260 non-null    int64
 1   codigo_iso                 260 non-null    object
 2   dias_con_heladas           260 non-null    int64
 3   eventos_extremos           118 non-null    object
 4   humedad_relativa_promedio  260 non-null    int64
 5   indice_aridez              260 non-null    float64
 6   meses_estres_hidrico       260 non-null    int64
 7   pais                       260 non-null    object
 8   precipitacion_total        260 non-null    int64
 9   region_nombre              260 non-null    object
 10  temperatura_maxima         260 non-null    float64
 11  temperatura_minima         260 non-null    float64
 12  temperatura_promedio       260 non-null    float64
dtypes: float64(4), int64(5), object(4)
memory usage: 26.5+ KB

In [15]:
df_politicas = pd.read_csv('datos/politicas_agricolas.csv')
df_politicas.head()

,codigo,nombre_pais,acuerdo_internacional_anio_firma,acuerdo_internacional_firmado,acuerdo_internacional_nombre,regulacion_anio_implementacion,regulacion_multa_hectarea,regulacion_porcentaje_minimo,regulacion_tipo,regulacion_vigente,subsidio_anio,subsidio_beneficiarios,subsidio_descripcion,subsidio_moneda,subsidio_monto,subsidio_Precio_euros,subsidio_tipo
0,ARG,Argentina,NaN,0,Convenio_Biodiversidad,2010,NaN,NaN,pesticidas_neonicotinoides,1,2019,7215,Subsidio para investigacion desarrollo,USD,15562206,14317229.52,investigacion_desarrollo
1,ARG,Argentina,NaN,0,Convenio_Biodiversidad,2010,NaN,NaN,pesticidas_neonicotinoides,1,2021,1914,Subsidio para maquinaria,USD,25542386,23498995.12,maquinaria
2,ARG,Argentina,NaN,0,Convenio_Biodiversidad,2010,NaN,NaN,pesticidas_neonicotinoides,1,2021,10823,Subsidio para fertilizantes,USD,32694726,30079147.92,fertilizantes
3,ARG,Argentina,NaN,0,Convenio_Biodiversidad,2010,NaN,NaN,pesticidas_neonicotinoides,1,2023,10898,Subsidio para expansion frontera agricola,USD,12595066,11587460.72,expansion_frontera_agricola
4,ARG,Argentina,NaN,0,Convenio_Biodiversidad,2012,NaN,NaN,uso_agua,0,2019,7215,Subsidio para investigacion desarrollo,USD,15562206,14317229.52,investigacion_desarrollo

In [16]:
df_politicas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 17 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   codigo                            159 non-null    object
 1   nombre_pais                       159 non-null    object
 2   acuerdo_internacional_anio_firma  95 non-null     float64
 3   acuerdo_internacional_firmado     159 non-null    int64
 4   acuerdo_internacional_nombre      159 non-null    object
 5   regulacion_anio_implementacion    159 non-null    int64
 6   regulacion_multa_hectarea         24 non-null     float64
 7   regulacion_porcentaje_minimo      23 non-null     float64
 8   regulacion_tipo                   159 non-null    object
 9   regulacion_vigente                159 non-null    int64
 10  subsidio_anio                     159 non-null    int64
 11  subsidio_beneficiarios            159 non-null    int64
 12  subsidio_descripcion              159 non-null    object
 13  subsidio_moneda                   159 non-null    object
 14  subsidio_monto                    159 non-null    int64
 15  subsidio_Precio_euros             159 non-null    float64
 16  subsidio_tipo                     159 non-null    object
dtypes: float64(4), int64(6), object(7)
memory usage: 21.2+ KB

### 3. Datos no estructurados

In [17]:
df_noticias = pd.read_csv('datos/noticias_agricolas.csv')
df_noticias.head()

,id_noticia,Alemania,Argentina,Australia,Brasil,Canadá,España,Estados Unidos,India,Italia,...,China,categoria,contenido,Año,Mes,Día,fuente,impacto_cultivos,severidad,titular
0,NEWS6582,0,0,0,0,0,1,0,0,1,...,0,clima,Eventos climáticos extremos están afectando la...,2021,septiembre,23,Bloomberg Commodities,Café,media,Sequía afecta proyecciones de cosecha en Kenia
1,NEWS8516,0,0,0,0,0,1,0,0,0,...,0,clima,Eventos climáticos extremos están afectando la...,2022,octubre,23,World Grain,Maíz,baja,Heladas tardías dañan frutales en China
2,NEWS9993,0,0,0,0,0,0,0,0,1,...,0,clima,Eventos climáticos extremos están afectando la...,2021,diciembre,22,Meat+Poultry,Maíz,alta,Ola de calor reduce rendimientos de Maíz
3,NEWS2701,0,0,0,0,0,0,0,0,0,...,0,clima,Eventos climáticos extremos están afectando la...,2022,marzo,9,Farm Journal,trigo,baja,Inundaciones devastan cultivos en la región
4,NEWS2755,0,0,0,0,0,0,0,0,0,...,0,comercio,El gobierno de Alemania ha anunciado nuevas me...,2023,marzo,7,AgriCensus,todos,baja,Nueva política agrícola en Alemania busca mejo...

In [18]:
df_noticias.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_noticia        60 non-null     object
 1   Alemania          60 non-null     int64
 2   Argentina         60 non-null     int64
 3   Australia         60 non-null     int64
 4   Brasil            60 non-null     int64
 5   Canadá            60 non-null     int64
 6   España            60 non-null     int64
 7   Estados Unidos    60 non-null     int64
 8   India             60 non-null     int64
 9   Italia            60 non-null     int64
 10  Francia           60 non-null     int64
 11  Kenia             60 non-null     int64
 12  México            60 non-null     int64
 13  Nueva Zelanda     60 non-null     int64
 14  Rusia             60 non-null     int64
 15  China             60 non-null     int64
 16  categoria         60 non-null     object
 17  contenido         60 non-null     object
 18  Año               60 non-null     int64
 19  Mes               60 non-null     object
 20  Día               60 non-null     int64
 21  fuente            60 non-null     object
 22  impacto_cultivos  60 non-null     object
 23  severidad         60 non-null     object
 24  titular           60 non-null     object
dtypes: int64(17), object(8)
memory usage: 11.8+ KB

In [19]:
df_reporte = pd.read_csv('datos/reporte_plagas.csv')
df_reporte.head()

,Año,Mes,Día,Area_afectada,Cultivo,Eficacia,Pais,Perdida_estimada,Plaga_detectada,Region,Severidad,Tratamiento_Aplicado
0,2020,enero,1,2745,Arroz,93,China,26,Barrenador del tallo,Región Principal,Media,Químico (Epoxiconazole)
1,2020,enero,13,3943,Caña de azúcar,97,Francia,17,Chinche marrón,Región Principal,Crítica,Cultural (Control manual)
2,2020,enero,15,10,Maíz,82,Brasil,38,Oruga militar tardía,Cerrado,Alta,Cultural (Fecha de siembra ajustada)
3,2020,enero,18,3064,Maíz,83,Brasil,3,Barrenador del tallo,Mata Atlántica,Crítica,Biológico (Trichogramma spp.)
4,2020,enero,23,995,Soja,75,Argentina,2,Langosta,Patagonia,Media,Biológico (Trichogramma spp.)

In [20]:
df_reporte.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Año                   100 non-null    int64
 1   Mes                   100 non-null    object
 2   Día                   100 non-null    int64
 3   Area_afectada         100 non-null    int64
 4   Cultivo               100 non-null    object
 5   Eficacia              100 non-null    int64
 6   Pais                  100 non-null    object
 7   Perdida_estimada      100 non-null    int64
 8   Plaga_detectada       100 non-null    object
 9   Region                100 non-null    object
 10  Severidad             100 non-null    object
 11  Tratamiento_Aplicado  100 non-null    object
dtypes: int64(5), object(7)
memory usage: 9.5+ KB